#!/bin/bash

echo "🚀 Déploiement Facturo - Assistant automatique"
echo "==============================================="
echo ""
echo "Ce script va te guider pour déployer Facturo en 3 clics."
echo ""

# Étape 1 : Vérifier que le repo est public
echo "✅ Étape 1/3 : Vérification du repo..."
sleep 1
echo "   Repo: https://github.com/MoussaBoaz/facturo-demo"
echo "   Status: ✅ Public et prêt"
echo ""

# Étape 2 : Render
echo "📝 Étape 2/3 : Déploiement Backend (Render)"
echo "   Action requise de ta part :"
echo ""
echo "   1. Clique sur ce lien :"
echo "      https://dashboard.render.com/blueprint/new?repo=https://github.com/MoussaBoaz/facturo-demo"
echo ""
echo "   2. Connecte-toi avec GitHub (si pas encore fait)"
echo ""
echo "   3. Clique sur 'Apply' (Render détecte automatiquement render.yaml)"
echo ""
echo "   4. Attends 5 minutes (déploiement automatique)"
echo ""
echo "   URL finale: https://facturo-api.onrender.com"
echo ""
read -p "Appuie sur ENTRÉE quand tu as terminé l'étape 2..."
echo ""

# Étape 3 : Vercel
echo "📝 Étape 3/3 : Déploiement Frontend (Vercel)"
echo "   Action requise de ta part :"
echo ""
echo "   1. Clique sur ce lien magique :"
echo "      https://vercel.com/new/clone?repository-url=https://github.com/MoussaBoaz/facturo-demo&root-directory=frontend&framework=angular"
echo ""
echo "   2. Connecte-toi avec GitHub (si pas encore fait)"
echo ""
echo "   3. Dans 'Environment Variables', ajoute :"
echo "      Name:  API_URL"
echo "      Value: https://facturo-api.onrender.com/api"
echo ""
echo "   4. Clique sur 'Deploy'"
echo ""
echo "   URL finale: https://facturo-demo.vercel.app (ou similaire)"
echo ""
read -p "Appuie sur ENTRÉE quand tu as terminé l'étape 3..."
echo ""

# Récap
echo "🎉 DÉPLOIEMENT TERMINÉ !"
echo "======================="
echo ""
echo "URLs de ton SaaS Facturo :"
echo "   🌐 Frontend: https://facturo-demo.vercel.app"
echo "   ⚙️  Backend:  https://facturo-api.onrender.com"
echo "   📁 Code:     https://github.com/MoussaBoaz/facturo-demo"
echo ""
echo "Identifiants de test :"
echo "   Email:    demo@facturo.io"
echo "   Password: password123"
echo ""
echo "⚠️  Important : Les services Render/Vercel gratuits 'dorment' après 15 min d'inactivité."
echo "   Le premier chargement peut prendre 30-60 secondes."
echo ""
echo "Pour modifier le code :"
echo "   git clone https://github.com/MoussaBoaz/facturo-demo.git"
echo ""
